# Generated by Django 5.1.1 on 2024-10-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(default='Descrição não disponível', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(default='Teste', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
