# Generated by Django 5.1.1 on 2024-11-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playList', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='visibilidade',
            field=models.BooleanField(default=False),
        ),
    ]
