# Generated by Django 5.1.1 on 2025-09-15 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playList', '0005_video_visibilidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comentários'},
        ),
        migrations.CreateModel(
            name='VideoCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_by', to='playList.video')),
            ],
            options={
                'verbose_name': 'Vídeo Concluído',
                'verbose_name_plural': 'Vídeos Concluídos',
                'unique_together': {('user', 'video')},
            },
        ),
    ]
